

#include "ConfigLoader.h"


ConfigLoader::ConfigLoader(std::string config_file_path): 
config_file(config_file_path),
CONFIG()
{
    config_file >> CONFIG;
    config_file.close();

    WINDOW_TITLE = CONFIG["WINDOW_TITLE"];
    WINDOW_WIDTH = CONFIG["WINDOW_WIDTH"];
    WINDOW_HEIGHT = CONFIG["WINDOW_HEIGHT"];
    FRAME_RATE = CONFIG["FRAME_RATE"];
    BACKGROUND_COLOR.r = CONFIG["BACKGROUND_COLOR"][0];
    BACKGROUND_COLOR.g = CONFIG["BACKGROUND_COLOR"][1];
    BACKGROUND_COLOR.b = CONFIG["BACKGROUND_COLOR"][2];
    ANTIALIASING_LEVEL = CONFIG["ANTIALIASING_LEVEL"];
    BALL_RADIUS = CONFIG["BALL_RADIUS"];
    BALL_SPEED = CONFIG["BALL_SPEED"];
    BALL_COLOR.r = CONFIG["BALL_COLOR"][0];
    BALL_COLOR.g = CONFIG["BALL_COLOR"][1];
    BALL_COLOR.b = CONFIG["BALL_COLOR"][2];
    SHOW_COLLISION_SHAPES = CONFIG["SHOW_COLLISION_SHAPES"];
    PAD_WIDTH = CONFIG["PAD_WIDTH"];
    PAD_HEIGHT = CONFIG["PAD_HEIGHT"];
    PAD_COLOR.r = CONFIG["PAD_COLOR"][0];
    PAD_COLOR.g = CONFIG["PAD_COLOR"][1];
    PAD_COLOR.b = CONFIG["PAD_COLOR"][2];
    PAD_SENSIVITY = CONFIG["PAD_SENSIVITY"];
    PAD_COLLISION_MARGIN.x = CONFIG["PAD_COLLISION_MARGIN"];
    PAD_COLLISION_MARGIN.y = CONFIG["PAD_COLLISION_MARGIN"];
    WINDOW_COLLISION_PADDING.x = CONFIG["WINDOW_COLLISION_PADDING"];
    WINDOW_COLLISION_PADDING.y = CONFIG["WINDOW_COLLISION_PADDING"];
    SCORE_COUNTER_FONT_SIZE = CONFIG["SCORE_COUNTER_FONT_SIZE"];
    SCORE_COUNTER_COLOR.r = CONFIG["SCORE_COUNTER_COLOR"][0];
    SCORE_COUNTER_COLOR.g = CONFIG["SCORE_COUNTER_COLOR"][1];
    SCORE_COUNTER_COLOR.b = CONFIG["SCORE_COUNTER_COLOR"][2];
    ISLAND_WIDTH = CONFIG["ISLAND_WIDTH"];
    ISLAND_HEIGHT = CONFIG["ISLAND_HEIGHT"];
    ISLAND_COLOR.r = CONFIG["ISLAND_COLOR"][0];
    ISLAND_COLOR.g = CONFIG["ISLAND_COLOR"][1];
    ISLAND_COLOR.b = CONFIG["ISLAND_COLOR"][2];
    ISLAND_COLLISION_MARGIN.x = CONFIG["ISLAND_COLLISION_MARGIN"];
    ISLAND_COLLISION_MARGIN.y = CONFIG["ISLAND_COLLISION_MARGIN"];
    BALL_SPEED_MULTIPLIER = CONFIG["BALL_SPEED_MULTIPLIER"];
}

ConfigLoader::~ConfigLoader() {

}